version: '3.8'

services:
  db:
    container_name: postgres_db
    image: postgres:17
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: node_app
    build: ./app
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy

  # db web interface
  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080

volumes:
  postgres_data:
