version: '3.8'

services:
  db:
    container_name: ${POSTGRES_HOST}
    image: postgres:17
    restart: always
    env_file: .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - matcha_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    container_name: matcha_server
    build: ./app/server
    env_file: .env
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    volumes:
      - ./app/server:/app/server
      - ./app/server/node_modules:/app/server/node_modules
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "npm install && npm run dev"

  client:
    container_name: matcha_client
    build: ./app/client
    env_file: .env
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'
    volumes:
      - ./app/client:/app/client
      - ./app/client/node_modules:/app/client/node_modules
    depends_on:
      - server
    command: bash -c "npm install && npm run dev"

volumes:
  matcha_data:
